2021-03-18 03:57:42 info: ---------------------------------------
2021-03-18 03:57:42 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-03-18 03:57:42 info: ---------------------------------------
2021-03-18 03:57:48 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho --silent false --verbose false --reporters="/Users/nizamimursudlu/Desktop/hyf/Homework/test-runner/CustomReporter.js"
Error: expect(received).resolves.toEqual()

Received promise rejected instead of resolved
Rejected to value: [Error: You didn't pass in a first name!]
    at expect (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/expect/build/index.js:134:15)
    at Object.<anonymous> (/Users/nizamimursudlu/Desktop/hyf/Homework/3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:54:12)
    at Object.asyncJestTest (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm ERR! code 1
npm ERR! path /Users/nizamimursudlu/Desktop/hyf/Homework
npm ERR! command failed
npm ERR! command sh -c jest ex1-johnWho --silent false --verbose false '--reporters=/Users/nizamimursudlu/Desktop/hyf/Homework/test-runner/CustomReporter.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nizamimursudlu/.npm/_logs/2021-03-18T14_57_48_367Z-debug.log

2021-03-18 03:59:34 info: ---------------------------------------
2021-03-18 03:59:34 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-03-18 03:59:34 info: ---------------------------------------
2021-03-18 03:59:38 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho --silent false --verbose false --reporters="/Users/nizamimursudlu/Desktop/hyf/Homework/test-runner/CustomReporter.js"
Error: expect(received).resolves.toEqual()

Received promise rejected instead of resolved
Rejected to value: [Error: You didn't pass in a first name!]
    at expect (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/expect/build/index.js:134:15)
    at Object.<anonymous> (/Users/nizamimursudlu/Desktop/hyf/Homework/3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:54:12)
    at Object.asyncJestTest (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm ERR! code 1
npm ERR! path /Users/nizamimursudlu/Desktop/hyf/Homework
npm ERR! command failed
npm ERR! command sh -c jest ex1-johnWho --silent false --verbose false '--reporters=/Users/nizamimursudlu/Desktop/hyf/Homework/test-runner/CustomReporter.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nizamimursudlu/.npm/_logs/2021-03-18T14_59_38_398Z-debug.log

2021-03-18 04:01:12 info: Disclaimer turned off
2021-03-18 04:01:43 info: -------------------------------------------------
2021-03-18 04:01:43 info: >>> Running Unit Test `ex2-checkDoubleDigits` <<<
2021-03-18 04:01:43 info: -------------------------------------------------
2021-03-18 04:01:46 info: All unit tests passed.
2021-03-18 04:01:48 info: All steps were completed successfully
2021-03-18 04:02:19 info: ----------------------------------------
2021-03-18 04:02:19 info: >>> Running Unit Test `ex3-rollDice` <<<
2021-03-18 04:02:19 info: ----------------------------------------
2021-03-18 04:02:21 info: All unit tests passed.
2021-03-18 04:02:23 info: All steps were completed successfully
2021-03-18 04:02:58 info: --------------------------------------------
2021-03-18 04:02:58 info: >>> Running Unit Test `ex4-pokerDiceAll` <<<
2021-03-18 04:02:58 info: --------------------------------------------
2021-03-18 04:03:00 info: All unit tests passed.
2021-03-18 04:03:02 info: All steps were completed successfully
2021-03-18 04:03:24 info: ---------------------------------------
2021-03-18 04:03:24 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-03-18 04:03:24 info: ---------------------------------------
2021-03-18 04:03:29 error: *** Unit Test Error Report ***

Command failed: npx jest ex1-johnWho --silent false --verbose false --reporters="/Users/nizamimursudlu/Desktop/hyf/Homework/test-runner/CustomReporter.js"
Error: expect(received).resolves.toEqual()

Received promise rejected instead of resolved
Rejected to value: [Error: You didn't pass in a first name!]
    at expect (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/expect/build/index.js:134:15)
    at Object.<anonymous> (/Users/nizamimursudlu/Desktop/hyf/Homework/3-UsingAPIs/Week1/unit-tests/ex1-johnWho.test.js:54:12)
    at Object.asyncJestTest (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (<anonymous>)
    at mapper (/Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /Users/nizamimursudlu/Desktop/hyf/Homework/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
npm ERR! code 1
npm ERR! path /Users/nizamimursudlu/Desktop/hyf/Homework
npm ERR! command failed
npm ERR! command sh -c jest ex1-johnWho --silent false --verbose false '--reporters=/Users/nizamimursudlu/Desktop/hyf/Homework/test-runner/CustomReporter.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nizamimursudlu/.npm/_logs/2021-03-18T15_03_28_976Z-debug.log

2021-03-18 04:07:02 info: ---------------------------------------
2021-03-18 04:07:02 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-03-18 04:07:02 info: ---------------------------------------
2021-03-18 04:07:08 error: *** Unit Test Error Report ***

- getAnonName should take a single argument

2021-03-18 04:08:04 info: ---------------------------------------
2021-03-18 04:08:04 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-03-18 04:08:04 info: ---------------------------------------
2021-03-18 04:08:09 error: *** Unit Test Error Report ***

- getAnonName should take a single argument

2021-03-18 04:09:23 info: ---------------------------------------
2021-03-18 04:09:23 info: >>> Running Unit Test `ex1-johnWho` <<<
2021-03-18 04:09:23 info: ---------------------------------------
2021-03-18 04:09:28 error: *** Unit Test Error Report ***

- getAnonName should take a single argument

